version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "backend_development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - restaurante-network

  api:
    image: api
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "--binding=0.0.0.0"]
    environment:
      - DBHOST=database
      - DBUSER=postgres
      - DBPASS=password
      - CLOUDAMQP_URL=amqp://127.0.0.1:15672
      - WEBHOOK_URL=https://webhook.site/76d77748-495c-43f9-b664-00c100bdf226
      - REDIS_URL=redis://redis:6379/1
      - ALLOW_ORIGINS=http://localhost:3001
      - RAILS_ENV=development
    volumes:
      - ./backend:/rails
    ports:
      - "3000:3000"
    depends_on:
      - database
      - rabbitmq
      - redis
    networks:
      - restaurante-network

  rabbitmq:
    image: rabbitmq:3.13-rc-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - restaurante-network

  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    networks:
      - restaurante-network

networks:
  restaurante-network:
    driver: bridge

volumes:
  postgres: