version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "backend_development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - restaurante-network

  api:
    image: api
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "--binding=0.0.0.0"]
    environment:
      - DBHOST=database
      - DBUSER=postgres
      - DBPASS=password
    volumes:
      - ./backend:/rails
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - restaurante-network

networks:
  restaurante-network:
    driver: bridge

volumes:
  postgres: